### PR TITLE
master cert should use master.key_secret

### PR DESCRIPTION
**Pull request by cataglyphis**
change <master.key> to <master.key_secret> in MASTER_CERT

### CODE REVIEW

**Comment by ghost** [comment]
OK, correctly based on master, but as stated in #7 github pull requests cannot be merged as the code on github is just a mirror. Code changes with attributions need to go via review.linaro.org using git.linaro.org as covered in the docs and we do not yet have an automated way of creating a review based on a github pull request. A review for this change has already been created and merged into master on git.linaro.org. https://review.linaro.org/#/c/18386/ Again, the github mirror only gets updated when a production release is made, so there is nothing which can be done with this pull request (it would cause a conflict when the mirror is updated).

In a separate review, we are improving the docs on contributing via github: https://review.linaro.org/#/c/18390/3/doc/v2/development-intro.rst

**Comment by cataglyphis** [comment]
@codehelp So I must register with Linaro, then follow https://validation.linaro.org/static/docs/v2/development.html#development-workflow to submit patch? It is not very convenient actually, hope we can send pull requests to Linaro from GitHub in the future.

By the way, is it possible to list the function of each folder & file in the user manual of lava-server & lava-dispatcher? For example, in **/etc/lava-server** there are several folders, like *default*, *dispatcher-config*, *dispatcher.d*, *reports*, *templates*, *views*, and several files, like *env.yaml*, *instance.conf*, *lava-master* and so on. I think it's better to list the corresponding function of each folder & file, and which one is invalid in LAVA V1.

**Comment by ghost** [comment]
I know it is inconvenient but until https://projects.linaro.org/browse/LAVA-903 can be fixed, it is the only method. We can't use the github pull-request / review workflow, it lacks the support we need. (GitHub is not the best solution for every team.) Having two review systems is also unlikely to work. There is no timeline for LAVA-903 yet, we have a lot of more urgent priorities, including the removal of the V1 code.

I'll update the triage documentation to cover files and directories in /etc/: https://staging.validation.linaro.org/static/docs/v2/simple-admin.html#index-4 - the manpages will never cope with the amount of information actually required to administer a LAVA instance. Rather than identifying which ones are invalid in V1, the docs will simply list those which are used in V2.

**Comment by cataglyphis** [comment]
@codehelp sorry to disturb you again, according to https://validation.linaro.org/static/docs/v2/development-intro.html and https://validation.linaro.org/static/docs/v2/development.html#development-workflow, I plan to clone the latest code and submit patch, when run **git review -s**, then exception occurs. Do you know how to fix this issue, by the way I can not clone the code with ssh method even though I have already add the ssh-key to gerrit.

Could not connect to gerrit.
Enter your gerrit username: bo.wang
Trying again with ssh://bo.wang@review.linaro.org:29418/lava/lava-server
<traceback object at 0x7f4ea02bccf8>
We don't know where your gerrit is. Please manually create a remote
named "gerrit" and try again.

connect to host review.linaro.org port 29418: No route to host

**Pull request closed without merging**
